name: Bug report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - []
body:
  - type: markdown
    attributes:
      value: |
        ## Note that clairvoyancy does not exist ... if you provide no details to replicate = no response
  - type: checkboxes
    id: checked-docu
    attributes:
      label: Own Analysis
      description: I have read the documentation which did not provide help, neither from the HomeAssistant forum. 
      options:
        - label: I cannot find my issue in the documentation nor via the Forum
          required: true
        - label: The issue is not resolved with the latest (beta) release
          required: true
        - label: I understand that this repo has been created mainly to support critical bugs, I understand that my issue may not be fixed easily
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: A clear and concise description of what the bug is.
      description: |
        - has it worked before
        - what it does not do vs. expectation
      render: shell
    validations:
      required: true     
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell



