name: Feature Request
description: File a idea on how to increase the value.
title: "[FEATURE]: "
labels: ["feature", "triage"]
assignees: 
  - []
body:
  - type: markdown
    attributes:
      value: |
        Is your request really a feature or aiming to fix a bug, then raise a [BUG REPORT](https://github.com/vingerha/apexcharts-card/issues/new?assignees=&labels=bug%2Ctriage&projects=&template=bug_report.yml&title=%5BBug%5D%3A+)
  - type: checkboxes
    id: checked-docu
    attributes:
      label: Disclaimer
      description: I have done the pre-work before raising this
      options:
        - label: I cannot find a workaround via the [HOME ASSISTANT ForuM](https://community.home-assistant.io/t/apexcharts-card-a-highly-customizable-graph-card/272877)
          required: true
        - label: I understand that this repo has been created mainly to support critical bugs, I understand that my request may not be implemented
  - type: textarea
    id: description
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      render: shell
  - type: textarea
    id: considerations
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      render: shell
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      render: shell
